version: '3.8'
      
services:
  frontend:
    image: excersice1.12
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9090
    container_name: excersice2.3-frontend
    ports:
      - 9000:5000
  backend:
    environment:
    - PORT=8080
    - REQUEST_ORIGIN=http://localhost:9000
    image: excersice1.13
    container_name: excersice2.3-backend
    ports:
      - 9090:8080